### ISSUE TITLE
Not following numpy-style docstring

### ISSUE THREAD

**Issue by watakandai** [HIRO-group/roboskin#41]
when I run
```
sphinx-apidoc -f -o docs robotic_skin
sphinx-autobuild docs docs/_build/html
```

I get these errors.
These are due to the use of other docstring style.

```
WARNING: autodoc: failed to import module u'const' from module u'robotic_skin'; the following exception was raised:
libnlopt.so.0: cannot open shared object file: No such file or directory
WARNING: autodoc: failed to import module u'algorithm.convert_to_lowertriangular_matrix' from module u'robotic_skin'; the following exception was raised:
Traceback (most recent call last):
  File "/home/kandai/.local/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/home/kandai/Documents/github/robotic_skin/robotic_skin/algorithm/__init__.py", line 4, in <module>
    from .convert_to_lowertriangular_matrix import ConvertToLT
  File "/home/kandai/Documents/github/robotic_skin/robotic_skin/algorithm/convert_to_lowertriangular_matrix.py", line 106
    def numpyarray_toint(self, my_array: np.ndarray, reverse: bool):
                                       ^
SyntaxError: invalid syntax

| reading sources... [ 16%] index                                                                        reading sources... [100%] robotic_skin.sensoration                                                       
WARNING: autodoc: failed to import module u'algorithm' from module u'robotic_skin'; the following exception was raised:
Traceback (most recent call last):
  File "/home/kandai/.local/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/home/kandai/Documents/github/robotic_skin/robotic_skin/algorithm/__init__.py", line 4, in <module>
    from .convert_to_lowertriangular_matrix import ConvertToLT
  File "/home/kandai/Documents/github/robotic_skin/robotic_skin/algorithm/convert_to_lowertriangular_matrix.py", line 106
    def numpyarray_toint(self, my_array: np.ndarray, reverse: bool):
                                       ^
SyntaxError: invalid syntax

WARNING: autodoc: failed to import module u'accel_position' from module u'robotic_skin.calibration'; the following exception was raised:
libnlopt.so.0: cannot open shared object file: No such file or directory
WARNING: autodoc: failed to import module u'adxl335' from module u'robotic_skin.sensor'; the following exception was raised:
Traceback (most recent call last):
  File "/home/kandai/.local/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/home/kandai/Documents/github/robotic_skin/robotic_skin/sensor/adxl335.py", line 40
    def calibrate(self) -> None:
                        ^
SyntaxError: invalid syntax

WARNING: autodoc: failed to import module u'flexiforce' from module u'robotic_skin.sensor'; the following exception was raised:
libnlopt.so.0: cannot open shared object file: No such file or directory
WARNING: autodoc: failed to import module u'lsm6ds3_accel' from module u'robotic_skin.sensor'; the following exception was raised:
Traceback (most recent call last):
  File "/home/kandai/.local/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/home/kandai/Documents/github/robotic_skin/robotic_skin/sensor/lsm6ds3_accel.py", line 18
    def __init__(self, bus_num: int = 1, addr: int = 0x6b):
                              ^
SyntaxError: invalid syntax


Sphinx error:

```

**Comment by krishnachaitanya7** [comment]
Sorry, as this wouldn't run in Python2, I will remove type annotations, I had them enforced in my IDE for python3

**Comment by krishnachaitanya7** [comment]
The sphinx should run now!

**Comment by krishnachaitanya7** [comment]
Lemme know

**Comment by watakandai** [comment]
👍

**Comment by krishnachaitanya7** [comment]
Closing this issue too.
